apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    component: "pushgateway"
    app: prometheus
    release: prometheus
    chart: prometheus-14.11.1
    heritage: Helm
  name: prometheus-pushgateway
  namespace: NAMESPACE
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    component: "pushgateway"
    app: prometheus
    release: prometheus
  type: "ClusterIP"
  sessionAffinity: None

